# Generated by Django 2.2.5 on 2019-10-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
