# Generated by Django 2.2.5 on 2019-10-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('find_a_doctor', '0002_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('available', models.CharField(max_length=200)),
                ('booked', models.IntegerField()),
            ],
        ),
    ]
