# Generated by Django 2.2.5 on 2019-10-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_doctor', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='booked',
            field=models.IntegerField(blank=True),
        ),
    ]
